### ISSUE TITLE
returning NaN

### ISSUE THREAD

**Issue by pruggirello** [shitchell/qrng#1]
Hello, thanks for the awesome tool!! I appreciate the effort you've put into it. I have an issue here where I am trying to console.log a random number, but it returns NaN. I get a success response from the API as well as a string.

code is:
`let rn = new QRNG();
console.log(rn.getInteger(0, 2); //returns NaN`

**Comment by shitchell** [comment]
Thanks for the feedback! And my deepest apologies for the delayed response. This issue has been resolved.

It appears ANU moved their API to AWS at some point, and that broke this. The two updates on their end that needed addressing:
- requests are no longer CORS enabled, meaning no cross-site requests
- all requests require an API key (even if a free one)

To this end, I've (likely permanently) updated qrng.js to point at my personal API to basically act as a proxy to ANU's API. This brings two update notes:

## qrng.js pointing at my personal API
I created an endpoint on my personal API: `/qrng` (you can find the full URL in the javascript if you're curious). My API has CORS enabled so that qrng.js can be implemented on any website without regard for cross-domain restriction. This is a slight bummer; I like having javascript stuffs that isn't dependent on me paying for a server in case I get hit by a car or something, but ah well here we are. With that in mind, the code for this endpoint is basically:

```py
@route('/qrng')
def do_qrng():
    url = "https://api.quantumnumbers.anu.edu.au"
    key = "{{my API key}}"
    if request.query_string:
        # Tack on any query string parameters to our request to ANU
        url = f"{url}?{request.query_string}"

    print("QRNG: fetching", url)
    response = requests.get(f"{url}", headers={"x-api-key": key})
    print("QRNG: got", response.text)
    if response.ok:
        response_json = response.json()
        if response_json.get("success", False) is True:
            return _json_response(data=response_json.get("data"))
    return _json_response_error(
        "invalid response from ANU",
        data=response.text
    )
```

I'm completely revamping my personal API and will open source it in the next few months once I'm finished, that way both the frontend (qrng.js) and backend (the above endpoint) are freely available.

## tokens
Right now my endpoint is making use of a paid token. Thankfully, requests are pretty cheap ($0.005/request), so I'm not toooo worried about the cost... but I don't *completely* like the idea of paying for everyone's requests lol or having it set up the "wrong" way, so at some point I'll change this to default to a free token (100 free requests per month) with the option of setting your own API key. That would look something like:

```js
// NOTE: this code is demonstrative only and not yet implemented

const rng = QRNG(); // Use the default free token, limited to 100 requests per month shared across all users of qrng.js
const rngPaid = QRNG({"api-key": "ja9s8djfalskdjf9a8dsf9a8jdflk"}); // Use a personal API Key with unlimited API requests
```

Again, for now the above isn't implemented, and you have unlimited use of qrng.js through my personal paid token :) And who knows, when I do implement the option to use a personal API key, I might not set the default to the free 100 requests per month because that's just lame. I'm thinking I'll probably lean towards buying a 2nd API key and manually limit it to something like 10,000 requests per month so that people have a chance to use it before it runs out.
